### ISSUE TITLE
color prop not working

### ISSUE THREAD

**Issue by sarwan920** [drinkeewu/dr-vue-echarts#2]
Hello There,
Recently I got to use your great charts! but the main issue I am facing is that while using colors prop on pie chart it is not working.

**Comment by drinkeewu** [comment]
Hi~ ，i'm sorry about that. Thank you for your feedback, i will fix it as soon as possible.



发自我的iPhone


------------------ Original ------------------

**Comment by sarwan920** [comment]
Sure, I will check for the issue too, I will see if i can fix that

**Comment by drinkeewu** [comment]
> Sure, I will check for the issue too, I will see if i can fix that

Can you provide more info about the issue? for examle, the source code or sceenshort

**Comment by drinkeewu** [comment]
> Sure, I will check for the issue too, I will see if i can fix that

@sarwan920 Can you provide more info about the issue? for examle, the source code or sceenshort

**Comment by sarwan920** [comment]
Hi, 
as you can see in the following SS , that when i apply colors on line chart it turns their colors to gray, but on pie chart colors does nothing.
or may be using not in the right way?

And also why in line chart, chart is not starting from 0 it has empty space in the start? i tried changing parameters but does nothing


![colors](https://user-images.githubusercontent.com/47607107/100498705-02738280-3119-11eb-879e-cff460a00898.PNG)
![ss colors](https://user-images.githubusercontent.com/47607107/100498709-08696380-3119-11eb-9537-18c14c73add6.PNG)

**Comment by sarwan920** [comment]
Can you also please guide me regarding this code locally on my machine for testing purpose?
I totally new to this and trying to learn things.
Thank You

**Comment by drinkeewu** [comment]
> Hi,
> as you can see in the following SS , that when i apply colors on line chart it turns their colors to gray, but on pie chart colors does nothing.
> or may be using not in the right way?
> 
> And also why in line chart, chart is not starting from 0 it has empty space in the start? i tried changing parameters but does nothing
> 
> ![colors](https://user-images.githubusercontent.com/47607107/100498705-02738280-3119-11eb-879e-cff460a00898.PNG)
> ![ss colors](https://user-images.githubusercontent.com/47607107/100498709-08696380-3119-11eb-9537-18c14c73add6.PNG)
@sarwan920 You should pass the attributes to the component through ":colors=['green']" instead of “colors=['green']”, and you can check the detail from here [https://vuejs.org/v2/guide/syntax.html#Attributes](url)

**Comment by sarwan920** [comment]
Thank You for the response!
It was my mistake i was doing it in wrong way.
But colors are changing in Line Chart, and in Pie chart colors prop does nothing.

**Comment by drinkeewu** [comment]
> Thank You for the response!
> It was my mistake i was doing it in wrong way.
> But colors are changing in Line Chart, and in Pie chart colors prop does nothing.

@sarwan920  The Pie has a bug indeed, i have fixed it in version 1.0.14. You can update the package and  try it again. I will close this issue later.

**Comment by sarwan920** [comment]
Thank You So much bro.
I just updated and it is working great!

But still line chart has I guess issue with starting point.
check my above screenshot for line chart where chart is not starting from 0 but instead it is starting for almost after approx 10 values, I tried different values but that did nothing

**Comment by drinkeewu** [comment]
> Thank You So much bro.
> I just updated and it is working great!
> 
> But still line chart has I guess issue with starting point.
> check my above screenshot for line chart where chart is not starting from 0 but instead it is starting for almost after approx 10 values, I tried different values but that did nothing

About the problem of not starting from 0, you can read the document of echarts: [https://echarts.apache.org/en/index.html](url)

**Comment by sarwan920** [comment]
Thank You bro for the Help!
